[colors]
[colors.primary]
background = "#0e091b"
foreground = "#fffaf8"

[colors.normal]
black   = "#0e091b"
red     = "#db4343"
green   = "#df9c5e"
yellow  = "#d27445"
blue    = "#7930c3"
magenta = "#b559ba"
cyan    = "#456aff"
white   = "#ecdbd4"

[colors.bright]
black   = "#3a2e5c"
red     = "#ed8f8f"
green   = "#deb484"
yellow  = "#edbaa0"
blue    = "#b484e4"
magenta = "#e1b5e4"
cyan    = "#8ea7ff"
white   = "#fffaf8"

[colors.cursor]
text   = "#0e091b"
cursor = "#fffaf8"
