# Accent and UI colors
accent = "#7930c3"
active_border_color = "#b484e4"
active_tab_background = "#7930c3"

# Cursor colors
cursor = "#fffaf8"

# Primary colors
foreground = "#fffaf8"
background = "#0e091b"

# Selection colors
selection_foreground = "#0e091b"
selection_background = "#7930c3"

# Normal colors (ANSI 0-7)
color0 = "#1c1431"
color1 = "#db4343"
color2 = "#df9c5e"
color3 = "#d27445"
color4 = "#3183ff"
color5 = "#d43adf"
color6 = "#8e4ad2"
color7 = "#d6d3df"

# Bright colors (ANSI 8-15)
color8  = "#31264d"
color9  = "#ed8f8f"
color10 = "#daa76e"
color11 = "#edbaa0"
color12 = "#7ab4ff"
color13 = "#e1b5e4"
color14 = "#c4a2e6"
color15 = "#ffffff"
