# Background and foreground colors
background = #100711
foreground = #f9f9f9

# Standard colors
palette = 0=#100711
palette = 1=#db4343
palette = 2=#dd9148
palette = 3=#df9c5e
palette = 4=#6c6ae4
palette = 5=#c895c2
palette = 6=#5785b7
palette = 7=#e2c0bd

# Bright colors
palette = 8=#95559e
palette = 9=#ed8f8f
palette = 10=#efc094
palette = 11=#f1cdab
palette = 12=#b9b7f4
palette = 13=#e9d3e7
palette = 14=#97b5d7
palette = 15=#f9f9f9
