# Background and foreground colors
background = #0e091b
foreground = #fffaf8

# Standard colors
palette = 0=#0e091b
palette = 1=#db4343
palette = 2=#df9c5e
palette = 3=#d27445
palette = 4=#7930c3
palette = 5=#b559ba
palette = 6=#456aff
palette = 7=#ecdbd4

# Bright colors
palette = 8=#3a2e5c
palette = 9=#ed8f8f
palette = 10=#deb484
palette = 11=#edbaa0
palette = 12=#b484e4
palette = 13=#e1b5e4
palette = 14=#8ea7ff
palette = 15=#fffaf8
