$color = rgba(16, 7, 17, 1)
$inner_color = rgba(16, 7, 17, 0.66)
$outer_color = rgba(200, 149, 194, 1)
$font_color = rgba(249, 249, 249, 1)
$placeholder_color = rgba(249, 249, 249, 0.7)
$check_color = rgba(87, 133, 183, 1)
