background            #100711
foreground            #f9f9f9

# black
color0  #100711
color8  #95559e

# red
color1  #db4343
color9  #ed8f8f

# green
color2  #dd9148
color10 #efc094

# yellow
color3  #df9c5e
color11 #f1cdab

# blue
color4  #6c6ae4
color12 #b9b7f4

# magenta
color5  #c895c2
color13 #e9d3e7

#cyan
color6  #5785b7
color14 #97b5d7

#white
color7  #e2c0bd
color15 #f9f9f9


