background            #0e091b
foreground            #fffaf8

# black
color0  #0e091b
color8  #3a2e5c

# red
color1  #db4343
color9  #ed8f8f

# green
color2  #df9c5e
color10 #deb484

# yellow
color3  #d27445
color11 #edbaa0

# blue
color4  #7930c3
color12 #b484e4

# magenta
color5  #b559ba
color13 #e1b5e4

#cyan
color6  #456aff
color14 #8ea7ff

#white
color7  #ecdbd4
color15 #fffaf8


